-- MySQL Script generated by MySQL Workbench
-- Wed Oct 11 10:16:41 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema enseniasbd
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `enseniasbd` ;

-- -----------------------------------------------------
-- Schema enseniasbd
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `enseniasbd` ;
USE `enseniasbd` ;

-- -----------------------------------------------------
-- Table `enseniasbd`.`imagen`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `enseniasbd`.`imagen` ;

CREATE TABLE IF NOT EXISTS `enseniasbd`.`imagen` (
  `idImagen` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `link` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idImagen`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
